### PR TITLE
fix(auth): improve email/password login validation and error handling

### LINKED ISSUE #11: [Auth] Email/password login validation and error handling
### Implement correct client-side validation and error handling for the email/password login dialog to align with backend rules.

Scope:

- Apply email/password validation
- Block submit on client-side invalid input
- Map backend errors (401/422) to user-friendly messages
- Ensure refresh flow and cookies handling don’t cause extra requests after login
- Clean up console noise (no plaintext creds logging)

### Depends on backend task [[Auth] Implement email/password login[#242]](https://github.com/orgs/Space2Study-UA-4427-4288-01/projects/1/views/1?pane=issue&itemId=132185814&issue=Space2Study-UA-4427-4288-01%7CBackEnd-01%7C11)

### PR DESCRIPTION
**Pull request by alisa-korniienko**
### Summary:
Improved the frontend behavior for the email/password login flow.

### Changes:
- Refactored `LoginDialog` error handling logic to correctly display server-side messages (401, 422, 429).
- Added translation support for new backend error codes (`RATE_LIMIT_EXCEEDED`, `INCORRECT_CREDENTIALS`).
- Fixed Snackbar context to translate dynamic messages properly.
- Updated validation for email and password fields using `useForm` and helper text.
- Added proper text wrapping and spacing for validation messages in `LoginForm`.
- Enhanced UX: consistent spacing, better readability, and proper feedback for all edge cases.

### Result:
Now the login form:
- Validates inputs before sending requests.
- Displays localized error messages from backend.
- Handles rate-limit responses.
- Shows validation text clearly with improved layout.
image

### CODE REVIEW

File: src/containers/guest-home-page/login-dialog/LoginDialog.jsx [hunk 1]
```diff
@@ -18,23 +18,32 @@ const LoginDialog = () => {
...
-  const [loginUser] = useLoginMutation()
+  const [loginUser, { isLoading }] = useLoginMutation()
 
   const { handleSubmit, handleInputChange, handleBlur, data, errors } = useForm(
     {
       onSubmit: async () => {
         try {
-          await loginUser(data).unwrap()
+          const payload = {
+            email: (data.email || '').trim(),
```
Comment (AndiKot) [inline src/containers/guest-home-page/login-dialog/LoginDialog.jsx]: Email check is not mandatory as we have form validation

File: src/context/snackbar-context.tsx [hunk 2]
```diff
@@ -19,7 +19,7 @@ interface SnackBarProviderProps {
 
 interface SetAllertProps {
```
Comment (AndiKot) [inline src/context/snackbar-context.tsx]: There is a typo in the interface name.

File: src/context/snackbar-context.tsx [hunk 3]
```diff
@@ -19,7 +19,7 @@ interface SnackBarProviderProps {
...
   severity: AlertColor
-  message: string
+  message: string | React.ReactNode
```
Comment (AndiKot) [inline src/context/snackbar-context.tsx]: Why did you decid to add the ReactNode type?

File: src/context/snackbar-context.tsx (hunk 2 above)
Comment (alisa-korniienko) [reply src/context/snackbar-context.tsx]: Good catch! Fixed the typo from SetAllertProps to SetAlertProps and updated all usages.

File: src/containers/guest-home-page/login-dialog/LoginDialog.jsx (hunk 1 above)
Comment (alisa-korniienko) [reply src/containers/guest-home-page/login-dialog/LoginDialog.jsx]: Agree — since the form already validates the email field, an explicit fallback (email || '') is redundant.
The only reason for touching this field was to normalize input (remove accidental spaces).
So we can safely simplify it to:

email: data.email.trim()

This keeps the payload clean and predictable while relying on form-level validation to ensure correctness.

File: src/context/snackbar-context.tsx (hunk 3 above)
Comment (alisa-korniienko) [reply src/context/snackbar-context.tsx]: I added ReactNode to the message type to make the snackbar context more flexible and aligned with how Material UI’s <Alert> actually works.
By default, <Alert> accepts children: ReactNode, not just strings — which means it can render not only plain text but also JSX elements such as <Trans> components (for i18n with dynamic content), links, or formatted text.
Previously, when message was strictly a string, we couldn’t safely pass anything richer than plain text, even though MUI supports it.
Now, with string | React.ReactNode, we preserve backward compatibility (all existing string messages still work) and unlock the ability to render more complex alert messages when needed — without type casting or hacks.
It’s a small but meaningful improvement that keeps the context generic, reusable, and consistent with React best practices.

Comment (AndiKot) [reply src/context/snackbar-context.tsx]: I think this restriction was made on purpose and that is enough in case of project. But if you want to keep this, you need to remove the string definition, since it is contained in the ReactNode definition.

Comment (alisa-korniienko) [reply src/context/snackbar-context.tsx]: You’re right — in React.ReactNode already includes string, so string | React.ReactNode is redundant.
I kept ReactNode because the snackbar may need rich content (links, <Trans/>, line breaks, etc.). We only translate plain strings and render all other nodes as-is.
I’ll simplify the type to just React.ReactNode to remove the redundancy.

**Review by OlhenShu — APPROVED** [review]

**Review by AndiKot — APPROVED** [review]

**Review by KorolyovKN — APPROVED** [review]
